"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import Header from "./Components/Header";
import theme from "./chakra-ui-theme";
import { Open_Sans } from "next/font/google";

const open_sens = Open_Sans({ subsets: ['cyrillic-ext'] });

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>webpage</title>
      </head>
      <body style={open_sens.style} className={inter.className}>
        <CacheProvider >
          <ChakraProvider>
            <Header /> {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
